### ISSUE TITLE
Only adds fuel lines to half of the outer stages in 1.0.2

### ISSUE THREAD

**Issue by blnk2007** [henrybauer/AutoAsparagus#2]

**Comment by henrybauer** [comment]
Have you seen this picture from the first post of the forum thread?

![](http://i.imgur.com/WbTpluj.png)

I think that's what you're describing, which is a known limitation.  If it's something else, please attach a screenshot and/or log.

**Comment by blnk2007** [comment]
Even when I do the symmetry properly AutoAsparagus doesn't work. In fact, using stock tanks and clicking asparagus connected fuel lines in the onion style and SmartStage did't work either.

Here are the logs and screenshots: https://www.dropbox.com/sh/jh4gzhwac8kgn00/AAAwTy0QZcpK6iA8MQonPzvNa?dl=0

**Comment by henrybauer** [comment]
Thanks for the logs and screenshots.  As mentioned, AutoAsparagus isn't properly recognizing the NovaPunch parts.  With the stock tanks, it did find the 4 tanks:

LOG 12:33:50.768] === AddFuelLines: Tanks to connect: 4 parts ===
[LOG 12:33:50.768] tank: fuelTank.long: -2616506/3/1
[LOG 12:33:50.769] tank: fuelTank.long: -2624774/3/1
[LOG 12:33:50.769] tank: fuelTank.long: -2625260/3/1
[LOG 12:33:50.769] tank: fuelTank.long: -2625746/3/1

Then it properly created one fuel line:

[LOG 12:33:50.770] === AttachFuelLine ===
[LOG 12:33:50.770] sourceTank: fuelTank.long: -2616506/3/1
[LOG 12:33:50.770] destTank: NBconeTank2m: -2611496/0/1
[...]
LOG 12:33:50.801] testing midway: (-5.32709000, 9.80740500, -4.60519700)
[LOG 12:33:50.801] ***\* fuel line is obstructed at (-1.46, 14.65, -1.07) by: NP.lft.25m.12m: -2611602/0/13
[LOG 12:33:50.801] New midway is: (-1.32709000, 13.80740000, -0.60519740)
[LOG 12:33:50.801] startPosition: (-1.86712100, 11.69500000, -0.60519760)
[LOG 12:33:50.801] destPosition: (-0.54023890, 16.88528000, -0.60519710)
[LOG 12:33:50.801]     attach to source tank
[LOG 12:33:50.801]     attach to destination: NBconeTank2m: -2611496/0/1
[LOG 12:33:50.801]     targetposition
[LOG 12:33:50.801]     direction
[LOG 12:33:50.801]     adding to ship
[LOG 12:33:50.801]     added to fuelSetsToConnect, total: 1

Then when it went to create the second fuel line, Unity threw an error:

[LOG 12:33:50.802] === AttachFuelLine ===
[LOG 12:33:50.802] sourceTank: fuelTank.long: -2624774/3/1
[LOG 12:33:50.802] destTank: fuelTank.long: -2616506/3/2
[LOG 12:33:50.827]     set position in space
[LOG 12:33:50.827] sourceTank: (-0.30772060, 9.82000000, 1.43354300)
[LOG 12:33:50.827]     dist: 1.44
[LOG 12:33:50.827] destTank: (-2.34646000, 9.82000000, -0.60519760)
[LOG 12:33:50.827]     dist: 1.44
[LOG 12:33:50.827] midway: (-1.32709000, 9.82000000, 0.41417260)
[LOG 12:33:50.827] testing midway: (-1.32709000, 9.82000000, 0.41417260)
[EXC 12:33:50.828] NullReferenceException
        UnityEngine.Collider.Internal_Raycast (UnityEngine.Collider col, Ray ray, UnityEngine.RaycastHit& hitInfo, Single distance)
        UnityEngine.Collider.Raycast (Ray ray, UnityEngine.RaycastHit& hitInfo, Single distance)
        AutoAsparagus.ASPFuelLine.fireRayAt (.Part p, Vector3 origin, Vector3 dest, UnityEngine.Vector3& collisionpoint)
        AutoAsparagus.ASPFuelLine.isFLpathObstructed (.Part sourceTank, .Part destTank, Vector3 midway)
        AutoAsparagus.ASPFuelLine.AttachFuelLine (.Part sourceTank, .Part destTank)
        AutoAsparagus.ASPFuelLine.makeFuelLineChain (System.Collections.Generic.List`1 tanksToConnect, .Part startTank)
        AutoAsparagus.ASPFuelLine.AddFuelLines ()
        AutoAsparagus.AutoAsparagus.OnGUI ()

That explains why the next time you clicked the button, it made it onion-style; one of the tanks already had a fuel line:

[LOG 12:33:50.832] Tank already has a fuel line: fuelTank.long: -2616506/3/2
[LOG 12:33:50.832] ... will connect tank: fuelTank.long: -2624774/3/1
[LOG 12:33:50.833] ... will connect tank: fuelTank.long: -2625260/3/1
[LOG 12:33:50.833] ... will connect tank: fuelTank.long: -2625746/3/1

We can't do asparagus staging with 3 fuel tanks, so it just wound up creating onion-style staging.

I don't know why the raycasting failed.  It should never fail.  I'll add some error handling around it and maybe we can see what the problem is.

If you have a .craft file you can share, I can try to reproduce this on my machine, which would help speed up debugging considerably.

**Comment by blnk2007** [comment]
Sure. https://www.dropbox.com/s/27c64qjqabvb3d9/BSRS%20I.craft?dl=0

**Comment by henrybauer** [comment]
Thanks, that test ship actually helped a lot.  I squashed a bunch of bugs, including the NullReferenceException - basically ProceduralFairings doesn't put a collider on its fairings, which may partially explain why I've always had problems with them.

I just put out a new release (https://github.com/henrybauer/AutoAsparagus/releases/latest), please try it and see if it works for you now

**Comment by blnk2007** [comment]
Awesome! I'll test it out.

**Comment by blnk2007** [comment]
That worked! Just have to make sure something other than the middle tank is root. It wouldn't work with a tank as root, but it did work as soon as I changed root to something else. The refresh is still a problem and I don't know if that is your issue, unity's, realchute's, or FAR's. I'll open that as a separate issue. :)
